### ISSUE TITLE
Tag "Forth"

### ISSUE THREAD

**Issue by FForth** [garethhubball/Fifth#1]
Please create a "forth" or/and "forth-like" tag and ... for this project. (Label "Manage topic" in open project)

**Comment by garethhubball** [comment]
I'll look into doing that at some point, not really sure that I want to draw attention to this at the moment though as I'm not able to support it nor PRs, it's more a personal project that I'm happy to share the code to right now if that makes sense?

**Comment by FForth** [comment]
https://cdn1.savepice.ru/uploads/2020/6/28/523f0c8ff3de4787152058d0816e8cd1-full.png
(Topics)
https://cdn1.savepice.ru/uploads/2020/6/28/50b3665206438db7b0d6514586414438-full.png

**Comment by garethhubball** [comment]
I'm still not ready to draw attention to the project as it's on ice, so closing for now as it's not really a serious project at this time.
